### ISSUE TITLE
Hard coded info/meta data in response

### ISSUE THREAD

**Issue by reisingerf** [aehrc/serverless-beacon#40]
Some values returned in the response via `getInfo` [here](https://github.com/aehrc/terraform-aws-serverless-beacon/blob/8dd8820075eeac2bc414d4a8741a747b599160cd/lambda/getInfo/lambda_function.py#L17-L55) should probably not be hard coded but configurable (including being left empty/not present). 

Some of them cause validation issues (e.g. in beacon network) when not filled as [expected](https://github.com/ga4gh-beacon/beacon-v2/blob/f3f93ef9f94f0164a185d36dd45045fc1a179c14/framework/json/responses/sections/beaconInfoResults.json).

**Comment by anuradhawick** [comment]
@reisingerf this is a work in progress.

However, I have added my WIP branch to this repo [here](https://github.com/aehrc/terraform-aws-serverless-beacon/tree/refactoring).

Please note that due to large changes I have done, I am unable to merge this work to `dev` branch quickly without testing. 

Until we test and merge the changes to `dev` you're welcome to use this branch. There could be bugs, but basic functions should work as expected.

I cannot make changes to `dev` branch directly at this point in time due as it would be a duplicate effort.

**Comment by anuradhawick** [comment]
Fixed in `dev`
